### ISSUE TITLE
[Bug]: Crash on start up

### ISSUE THREAD

**Issue by Sunekaer** [ShyNieke/StatuesMod#63]
### General Info

- [ ] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

38.0.15

### Mod version

1.7.7

### Java version

17.0.1

### Issue Description

Crash log: https://gist.github.com/Sunekaer/99405bc034bb75c5a7351c1a714f834e

**Comment by red2blue** [comment]
I also get this

```java

[19:39:33] [Thread-0/FATAL]: Statues' config just got changed on the file system!
[19:39:33] [Thread-0/INFO]: Common config re-baked
[19:39:34] [Forge Version Check/WARN]: Failed to process update information
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 5 column 4 path $..1.13.2.1
	at com.google.gson.Gson.fromJson(Gson.java:947) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:817) ~[gson-2.8.8.jar%2322!:?]
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:189) ~[fmlcore-1.18-38.0.17.jar%23275!:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:128) [fmlcore-1.18-38.0.17.jar%23275!:?]
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 5 column 4 path $..1.13.2.1
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:504) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:69) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar%2322!:?]
	... 6 more
	```

**Comment by Mrbysco** [comment]
> I also get this
> 
> ```java
> [19:39:33] [Thread-0/FATAL]: Statues' config just got changed on the file system!
> [19:39:33] [Thread-0/INFO]: Common config re-baked
> [19:39:34] [Forge Version Check/WARN]: Failed to process update information
> com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 5 column 4 path $..1.13.2.1
> 	at com.google.gson.Gson.fromJson(Gson.java:947) ~[gson-2.8.8.jar%2322!:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.8.jar%2322!:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:846) ~[gson-2.8.8.jar%2322!:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:817) ~[gson-2.8.8.jar%2322!:?]
> 	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:189) ~[fmlcore-1.18-38.0.17.jar%23275!:?]
> 	at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
> 	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:128) [fmlcore-1.18-38.0.17.jar%23275!:?]
> Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 5 column 4 path $..1.13.2.1
> 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.8.jar%2322!:?]
> 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:504) ~[gson-2.8.8.jar%2322!:?]
> 	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413) ~[gson-2.8.8.jar%2322!:?]
> 	at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:69) ~[gson-2.8.8.jar%2322!:?]
> 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar%2322!:?]
> 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187) ~[gson-2.8.8.jar%2322!:?]
> 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.8.jar%2322!:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar%2322!:?]
> 	... 6 more
> 	```
> ```

That's unrelated to this crash.
